### ISSUE TITLE
Issue when saving after using the "Download Manifest" option

### ISSUE THREAD

**Issue by Nicezki** [XyLe-GBP/MLTDABD-Rel#1]
Hello, first I want to say thank you for your awesome tool it's really helpful to me
but I saw a little bug using the "Download Manifest" option
**Version:** 1.0.0.0-Beta
**Steps:**
1. Open MLTDABD-Rel.exe
2. Go to File >> Download Manifest
3. Select any version to download (I use CloudFront latest android) and hit OK
4. "Save as" popup will appears but can't really save it 
Popup says: 
_File (Filepath)\xxxxxx.data does not exist.
Verify that the correct file name was given._

![MLTDABD-Rel_cyth220602_033149964_iuDpXnY8Ip](https://user-images.githubusercontent.com/38764429/171497994-d0675e0c-208f-421c-8d9b-694b865e4326.png)

**Expected result:**
The file should be created and saved without this popup

**A workaround that I use**
I create blank xxxxxx.data file before I use "Download Manifest" and save (to replace) the file
![image](https://user-images.githubusercontent.com/38764429/171497920-1c0d0184-c2c5-48bb-9a2a-b37a8596b88a.png)

**Comment by XyLe-GBP** [comment]
This minor bug will be fixed in the near future, so please be patient.
Thank you for reporting the bug.

**Comment by Nicezki** [comment]
Can confirm this problem is fixed after [the update](https://github.com/XyLe-GBP/MLTDABD-Rel/releases/tag/v1.1.2220.613)
![image](https://user-images.githubusercontent.com/38764429/173565029-f673a681-0b15-42c1-876e-c405e1d5bab1.png)

Thank you~♥
